# Generated by Django 2.1.7 on 2019-02-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='name',
        ),
    ]
