# Generated by Django 2.1.7 on 2019-02-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_manager', '0002_auto_20190218_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user',
            new_name='organisor',
        ),
    ]
